### PR TITLE
Use kadi dither state as authoritative

### LINKED ISSUE #346: In case of mismatch between kadi dither and History starcheck may just fail
Copying the comment in from

https://github.com/sot/starcheck/pull/304#issuecomment-528945415

It looks like for SEP0619B, we ran into a condition where the kadi commanded states dither state didn't match the History
```
Dither status in kadi commands does not match DITHER history
```

And the dither amplitudes were left undefined when passed to proseco to determine P2 values causing a TypeError

```
 at ./starcheck/src/starcheck.pl line 45.
	main::__ANON__("TypeError: unsupported operand type(s) for +: 'NoneType' and "...) called at (eval 80) line 3
	Ska::Starcheck::Obsid::proseco_probs("__main__", "proseco_probs", HASH(0x4888800)) called at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2997
	Ska::Starcheck::Obsid::set_proseco_probs_and_check_P2(Ska::Starcheck::Obsid=HASH(0x6de59d0)) called at ./starcheck/src/starcheck.pl line 690
```
Whichever way we decide to go, we should probably configure so either History or kadi commands "wins" and makes some kind of dither states for starcheck to proceed (with big red warnings or whatever).

This was also a problem in my first runs of MAY2620A, without a correct dither disable in cmd_states cmds (but dither disabled in History).

### PR DESCRIPTION
**Pull request by jeanconn**
## Description
Use kadi command states dither state as authoritative

Fixes #346 

### Unit tests

- [x] No unit tests

### Functional tests

Ran on AUG2322 schedule with the History without the dither disable in history before load start.

Flight starcheck errors
```
ska3-jeanconn-fido> ./sandbox_starcheck -dir /tmp/AUG2322A/ -out flt_aug2322a
Using backstop file /tmp/AUG2322A//CR235_1001.backstop
Using guide summary file /tmp/AUG2322A//mps/mgAUG2322A.sum
Using OR file /tmp/AUG2322A//mps/or/AUG2322_A.or
Using maneuver file /tmp/AUG2322A//mps/mmAUG2322A.sum
Using DOT file /tmp/AUG2322A//mps/mdAUG2322A.dot
Using mech check file /tmp/AUG2322A//output/TEST_mechcheck.txt
Using fidsel file /tmp/AUG2322A//History/FIDSEL.txt
Using dither file /tmp/AUG2322A//History/DITHER.txt
Using radmon file /tmp/AUG2322A//History/RADMON.txt
Using simtrans file /tmp/AUG2322A//History/SIMTRANS.txt
Using simfocus file /tmp/AUG2322A//History/SIMFOCUS.txt
Using attitude file /tmp/AUG2322A//History/ATTITUDE.txt
Using characteristics file /tmp/AUG2322A//mps/ode/characteristics/CHARACTERIS_18JAN21
Using aimpoint file /tmp/AUG2322A//output/AUG2322A_dynamical_offsets.txt
Using config file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/characteristics.yaml
Using odb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/fid_CHARACTERISTICS
Using agasc_file file /proj/sot/ska3/flight/data/agasc/proseco_agasc_1p7.h5
Using manerr file /tmp/AUG2322A//output/AUG2322A_ManErr.txt
Using processing summary file /tmp/AUG2322A//mps/msAUG2322A.sum
Using TLR file /tmp/AUG2322A//CR235_1001.tlr
Using banned_agasc file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/agasc.bad
Using bad_pixel file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/ACABadPixels
Using acq_star_rdb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/bad_acq_stars.rdb
Using gui_star_rdb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/bad_gui_stars.rdb
Dither status in kadi commands does not match DITHER history
Read 258 ACA bad pixels from /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/ACABadPixels
Read 46 bad AGASC IDs from /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/agasc.bad
#####################################################################
# calc_ccd_temps run at Wed Aug 24 14:43:50 2022 by jeanconn
# Continuity run_start_time = 2022:236:18:43:50.272
# calc_ccd_temps version = 13.15.2.dev5+g5fd629a
# chandra_models version = 3.40.2
# kadi version = 6.0.1
#####################################################################

Using backstop file /tmp/AUG2322A/CR235_1001.backstop
Found 1327 backstop commands between 2022:235:10:32:00.000 and 2022:240:21:55:12.436
RLTT = 2022:235:10:32:00.000
sched_stop = 2022:240:21:55:12.436
Fetching telemetry between 2022:230:18:35:17.669 and 2022:231:18:35:17.669
Calculating ACA thermal model
Propagation initial time and ACA: 2022:231:18:20:06.816 -8.65
Making temperature check plots
Writing plot file flt_aug2322a/ccd_temperature.png
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int' at line 45
 at ./starcheck/src/starcheck.pl line 37.
	main::__ANON__("TypeError: unsupported operand type(s) for +: 'NoneType' and "...) called at (eval 79) line 3
	Ska::Starcheck::Obsid::proseco_probs("__main__", "proseco_probs", HASH(0x556c3b650978)) called at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2896
	Ska::Starcheck::Obsid::set_proseco_probs_and_check_P2(Ska::Starcheck::Obsid=HASH(0x556c3d011720)) called at ./starcheck/src/starcheck.pl line 536

```

The new code puts error to console and starcheck html/txt report but finishes and uses the kadi state as authoritative. (uninitialized errors since fixed in master so this could be rebased but that is benign)

```
ska3-jeanconn-fido> git checkout dither-history
Branch 'dither-history' set up to track remote branch 'dither-history' from 'origin'.
Switched to a new branch 'dither-history'
ska3-jeanconn-fido> ./sandbox_starcheck -dir /tmp/AUG2322A/ -out flt_aug2322a
Using backstop file /tmp/AUG2322A//CR235_1001.backstop
Using guide summary file /tmp/AUG2322A//mps/mgAUG2322A.sum
Using OR file /tmp/AUG2322A//mps/or/AUG2322_A.or
Using maneuver file /tmp/AUG2322A//mps/mmAUG2322A.sum
Using DOT file /tmp/AUG2322A//mps/mdAUG2322A.dot
Using mech check file /tmp/AUG2322A//output/TEST_mechcheck.txt
Using fidsel file /tmp/AUG2322A//History/FIDSEL.txt
Using dither file /tmp/AUG2322A//History/DITHER.txt
Using radmon file /tmp/AUG2322A//History/RADMON.txt
Using simtrans file /tmp/AUG2322A//History/SIMTRANS.txt
Using simfocus file /tmp/AUG2322A//History/SIMFOCUS.txt
Using attitude file /tmp/AUG2322A//History/ATTITUDE.txt
Using characteristics file /tmp/AUG2322A//mps/ode/characteristics/CHARACTERIS_18JAN21
Using aimpoint file /tmp/AUG2322A//output/AUG2322A_dynamical_offsets.txt
Using config file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/characteristics.yaml
Using odb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/fid_CHARACTERISTICS
Using agasc_file file /proj/sot/ska3/flight/data/agasc/proseco_agasc_1p7.h5
Using manerr file /tmp/AUG2322A//output/AUG2322A_ManErr.txt
Using processing summary file /tmp/AUG2322A//mps/msAUG2322A.sum
Using TLR file /tmp/AUG2322A//CR235_1001.tlr
Using banned_agasc file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/agasc.bad
Using bad_pixel file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/ACABadPixels
Using acq_star_rdb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/bad_acq_stars.rdb
Using gui_star_rdb file /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/bad_gui_stars.rdb
Dither status in kadi commands does not match DITHER history
kadi 'DISA' ; History 'ENAB' 
Read 258 ACA bad pixels from /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/ACABadPixels
Read 46 bad AGASC IDs from /proj/sot/ska/jeanproj/git/starcheck/starcheck/data/agasc.bad
#####################################################################
# calc_ccd_temps run at Wed Aug 24 14:47:20 2022 by jeanconn
# Continuity run_start_time = 2022:236:18:47:19.585
# calc_ccd_temps version = 13.15.2.dev2+g22f4682
# chandra_models version = 3.40.2
# kadi version = 6.0.1
#####################################################################

Using backstop file /tmp/AUG2322A/CR235_1001.backstop
Found 1327 backstop commands between 2022:235:10:32:00.000 and 2022:240:21:55:12.436
RLTT = 2022:235:10:32:00.000
sched_stop = 2022:240:21:55:12.436
Fetching telemetry between 2022:230:18:35:17.669 and 2022:231:18:35:17.669
Calculating ACA thermal model
Propagation initial time and ACA: 2022:231:18:20:06.816 -8.65
Making temperature check plots
Writing plot file flt_aug2322a/ccd_temperature.png
Checking star catalog for obsid 45316
Checking star catalog for obsid 45315
Checking star catalog for obsid 25108
Checking star catalog for obsid 26079
Checking star catalog for obsid 25308
Checking star catalog for obsid 26003
Checking star catalog for obsid 23504
Checking star catalog for obsid 27268
Checking star catalog for obsid 45314
Checking star catalog for obsid 45313
Checking star catalog for obsid 45311
Checking star catalog for obsid 45310
Checking star catalog for obsid 45309
Checking star catalog for obsid 23786
Checking star catalog for obsid 24029
Checking star catalog for obsid 24030
Checking star catalog for obsid 24031
Checking star catalog for obsid 24032
Checking star catalog for obsid 24033
Checking star catalog for obsid 26213
Checking star catalog for obsid 27270
Checking star catalog for obsid 25929
Checking star catalog for obsid 25853
Checking star catalog for obsid 23878
Checking star catalog for obsid 27269
Checking star catalog for obsid 45308
Checking star catalog for obsid 45307
Checking star catalog for obsid 45305
Checking star catalog for obsid 45304
Checking star catalog for obsid 45303
Checking star catalog for obsid 27267
Checking star catalog for obsid 25841
Checking star catalog for obsid 27266
Checking star catalog for obsid 24519
Use of uninitialized value $n_acq in sprintf at ./starcheck/src/starcheck.pl line 701.
Use of uninitialized value $n_acq in sprintf at ./starcheck/src/starcheck.pl line 701.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2292.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2292.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2295.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2292.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2292.
Use of uninitialized value in sprintf at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2295.
Wrote HTML report to flt_aug2322a.html
Wrote text report to flt_aug2322a.txt
```

### CODE REVIEW

File: starcheck/src/lib/Ska/Parse_CM_File.pm [hunk 1]
```diff
@@ -121,20 +123,23 @@ sub dither {
...
+        }
 
-    # Confirm that last state matches kadi continuity ENAB/DISA.
-    # Otherwise, return string error and undef dither history.
-    if ($kadi_dither->{'dither'} ne $dh_state[-1]){
-        return ("Dither status in kadi commands does not match DITHER history\n", undef);
+        # Confirm that last state matches kadi continuity ENAB/DISA.
+        # Otherwise, return string error and undef dither history.
+        if ($kadi_dither->{'dither'} ne $dh_state[-1]){
+            $dither_error = "Dither status in kadi commands does not match DITHER history\n"
```
Comment (taldcroft) [inline starcheck/src/lib/Ska/Parse_CM_File.pm:136]: I would take out that newline as it comfortably fits on one line.

Comment (taldcroft) [reply starcheck/src/lib/Ska/Parse_CM_File.pm:136]: Is this error shown in red in the HTML report? Otherwise there is a good chance I'd miss it in review. Or I thought there was some section for overall processing errors that this could go in?

**Review by taldcroft — COMMENTED** [review]
The code and testing looks fine, I'm just wondering about making this situation pop so I'll notice it.

File: starcheck/src/lib/Ska/Parse_CM_File.pm (hunk 1 above)
Comment (jeanconn) [reply starcheck/src/lib/Ska/Parse_CM_File.pm:136]: Oh, and I'll check that newline... I run into the issue that the silly Prev Next links in starcheck will move around if the text block is too wide even if it could fit in a modern browser.

**Review by taldcroft — APPROVED** [review]
